# Generated by Django 3.0.2 on 2020-04-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('healthChange', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startSlide', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=256)),
                ('winningSlide', models.BooleanField(default=False)),
                ('adventureContainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.AdventureContainer')),
            ],
        ),
        migrations.CreateModel(
            name='NextSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Choice', unique=True)),
                ('nextSlide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='GoBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curSlide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Slide', unique=True)),
                ('prevSlide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.GoBack')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceContainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.ChoiceContainer'),
        ),
    ]
