branches:
  only:
  - master
  - stable
  
language: python
python:
  - "3.7"
env:
  - DJANGO=2.2 DB=sqlite
  - DJANGO=3.0 DB=sqlite
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
