# Generated by Django 3.0.4 on 2020-05-15 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200514_1907'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highestWinningHealth', models.IntegerField(default=0)),
                ('timesPlayed', models.IntegerField(default=0)),
                ('timesWon', models.IntegerField(default=0)),
                ('timesLost', models.IntegerField(default=0)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.AdventureContainer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
