# Generated by Django 3.0.4 on 2020-05-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurecontainer',
            name='timesLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurecontainer',
            name='timesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurecontainer',
            name='timesWon',
            field=models.IntegerField(default=0),
        ),
    ]
