# Generated by Django 3.0.2 on 2020-04-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicecontainer',
            name='curSlide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creator.Slide'),
        ),
        migrations.AlterField(
            model_name='nextslide',
            name='fromChoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creator.Choice'),
        ),
    ]
