# Generated by Django 3.0.2 on 2020-04-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200419_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pathAssigned',
            field=models.BooleanField(default=False),
        ),
    ]
