# Generated by Django 3.0.4 on 2020-05-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200514_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
