# Generated by Django 2.2.5 on 2020-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_messages_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='category',
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=42),
        ),
        migrations.AddField(
            model_name='messages',
            name='tags',
            field=models.ManyToManyField(to='forums.PostTags'),
        ),
    ]
